name: Run Reddit to Discord Bot

on:
  # Cho phép chạy thủ công từ giao diện GitHub
  workflow_dispatch:
  
  # Tự động chạy theo lịch (mỗi 10 phút)
  schedule:
    - cron: '*/10 * * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run Bot
        env:
          REDDIT_CLIENT_ID: Uy97AsZRhImy0TDzmaWjWw
          REDDIT_CLIENT_SECRET: NkdrNP9448hzfKZj2tWfBl2MfYylkA
          DISCORD_TOKEN: 6GGHrs31JlClHjkuwiQaO0pfJxoVUkub
          DISCORD_CHANNEL_ID: 1390197420771639316
          ADMIN_USER_ID: 1385489423612776501
        run: python bot.py
